### ISSUE TITLE
direct album play button

### ISSUE THREAD

**Issue by payback007** [jcorporation/myMPD#359]
Is it possible to implement a direct play button in the middle of an album cover? Means direct click into middle of album cover replaces the queue and start playing, clicking into the corner of an album cover access into album as implemented now.

**Comment by jcorporation** [comment]
I don‘t think that this is good for usability, especially for mobile devices. A play button on hover at the bottom could be the better way.

**Comment by payback007** [comment]
Yes, also good point. At the bottom of an album it is also a good idea. The idea was only to play the album in a more direct/handy way on a tablet. Accessing "replace queue" within the text box is sometimes a little bit unsuable on a wall mounted tablet. Hover with play button to replace queue by the full album should be more easy I think.

**Comment by jcorporation** [comment]
Hm, on hover works only with a mouse not with touch devices.

**Comment by payback007** [comment]
Hm, any other idea? The text fields are not so easy access on wall mounted display. It would be much more easy if there could be a possiblity "touch album = replace queue".

Is there a possibility for a configurable option?
- touch of album -> same as now
- touch of album -> replace queue

Or another idea
- short touch of album -> same as now
- long touch on album -> replace queue

**Comment by jcorporation** [comment]
Eventually is a static button the best solution. I will try ist and show if it is looking good.

**Comment by jcorporation** [comment]
I added a direct play button to the album view. It is displayed permanently on mobile devices and on hover on other devices.

**Comment by payback007** [comment]
Just tried out the new dev-Version! Looks very good and is working in pricipal as expected. Thank you very much for your work on it!

But there seem to be a little bug:
1) open 1st time of database -> displaying 1 "play button"
2) open 2nd time ot database adds one aditional play button -> displaying 2 "play button" next to each other
3) open 3rd time of database adds one aditional play button again -> displaing 3 "play button" next to each other

Increasing cover size -> adds always more "play buttons" next to each other until the cover space is reached from left to the right.

**Comment by jcorporation** [comment]
Should be now fixed in devel.

**Comment by payback007** [comment]
Unfortunately it's still the same behaviour. Changing between database and any other side adds one additional "play button".

**Comment by jcorporation** [comment]
You should try ./build.sh cleanupdist and rebuild again. In devel the dist files are not uptodate.

**Comment by payback007** [comment]
Yeah, looks and working great now!
