### ISSUE TITLE
Embedded albumart not displayed (readpicture command)

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#521]
myMPD Version: 8.0.0 (from 06 Jul 2021)
MPD Version: 0.22.9
Connection	/var/run/mpd/socket
Protocol version	0.22.4
Libmpdclient version	2.20.0
Libmympdclient version	1.0.6

Steps taken:
mpd loglevel set to "verbose" and started it -> mpd.txt
mympd loglevel set to "7" and started it -> mympd.txt

Browser used: Edge
browsed albums
Picked an album (Ella Fitzgerald & Louis  - Porgy & Bess
(m4a ALAC)) with no albumart shown. Extracted a folder.jpg
with mpc readpicture which is viewable with myMPDs
"Browse directories" function.

This is the same as #518 but with 8.0.0.
Please let me know if any further information is required.

myMPD has quickly become my favourite mpd client, many thanks for the excellent work!

[mympd.txt](https://github.com/jcorporation/myMPD/files/6785653/mympd.txt)
[mpd.txt](https://github.com/jcorporation/myMPD/files/6785654/mpd.txt)

**Comment by jcorporation** [comment]
I can not find the request for the albumart, I see only startup messages. Is the file truncated?

**Comment by GK-774** [comment]
mpd log or mympd log ? The logfiles cover the time from mpd/mympd start to "browse albums". mpc readpicture on the command line I did later, just to verify that there is albumart which can be extracted with the readpicture command.

**Comment by jcorporation** [comment]
Both, last line of mympd.txt is incomplete. 

`Jul 08 16:08:23 mpd.local mympd[299037]: WARN     mpdworker /root/rpmbuild/BUILD/myMPD-8.0.0/src/mpd_worker/mpd_worker_cache.c:154: Albumcache, skipping "werner/Compilations/_The Pearl fis`

**Comment by GK-774** [comment]
2nd try, now covers the full cycle:
mympd/mpd stop - start - browse albums (when albucache ready) - mpc readpicture - stop
[mympd2.txt](https://github.com/jcorporation/myMPD/files/6786016/mympd2.txt)
[mpd2.txt.gz](https://github.com/jcorporation/myMPD/files/6786019/mpd2.txt.gz)

**Comment by jcorporation** [comment]
This logs are good and I found the error: 
`Jul 08 18:21:32 mpd.local mympd[331900]: DEBUG    webserver /root/rpmbuild/BUILD/myMPD-8.0.0/src/web_server/web_server_albumart.c:208: Mimetype of /var/lib/mpd/music/werner/Ella Fitzgerald & Louis Armstrong/Porgy & Bess/01 Overture.m4a is application/octet-stream`

What image format is embedded? myMPD has only a limited support of image formats.

**Comment by jcorporation** [comment]
I found two bugs that are now fixed. Can you please try again?

**Comment by GK-774** [comment]
Well, now at least the covercache directory is more populated,
78 instead of one or two (sometimes none at all) files, but with
a total of 8160 albums still not a plausible number.
The albumart for the 01 Overture.m4a mentioned above is not among them.
I will try/test in more depth on Monday. Have a nice weekend!

**Comment by GK-774** [comment]
Take 3: Removed the existing folder.jpg from four directories (albums),
the paths are listed shown-not_shown.txt in the zip containing the logs.
Two albums worked ok, two did not.
Verified that mpc readpicture worked with all four.
[shown-not_shown.zip](https://github.com/jcorporation/myMPD/files/6810413/shown-not_shown.zip)
[mympd_log3.zip](https://github.com/jcorporation/myMPD/files/6810414/mympd_log3.zip)

**Comment by GK-774** [comment]
The mpd logs (had to split them and add .zip at the end to upload them).
[mpd_log3.zip.001.zip](https://github.com/jcorporation/myMPD/files/6810598/mpd_log3.zip.001.zip)
[mpd_log3.zip.002.zip](https://github.com/jcorporation/myMPD/files/6810600/mpd_log3.zip.002.zip)
[mpd_log3.zip.003.zip](https://github.com/jcorporation/myMPD/files/6810602/mpd_log3.zip.003.zip)
[mpd_log3.zip.004.zip](https://github.com/jcorporation/myMPD/files/6810606/mpd_log3.zip.004.zip)

**Comment by jcorporation** [comment]
Strange the logs showing no error extracting the albumart. Is the file `/var/lib/mympd/covercache/werner_Symon Bychkov_Heldenleben + 2_ Symph_ Larcher (Kenotap_1-01 Titel 01 - Strauss_m4a.jpg` a valid image?

The difference between myMPD and mpc is:
myMPD uses the readalbumart implementation from libmpdclient, mpc uses the more generic binary command, but the readalbumart is based on the binary command.

**Comment by GK-774** [comment]
...a valid image?
Yes, displays just fine and file says:
file werner_Symon\ Bychkov_Heldenleben\ +\ 2_\ Symph_\ Larcher\ \(Kenotap_1-01\ Titel\ 01\ -\ Strauss_m4a.jpg 
werner_Symon Bychkov_Heldenleben + 2_ Symph_ Larcher (Kenotap_1-01 Titel 01 - Strauss_m4a.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=10, manufacturer=Canon, model=Canon MB5100 series Network, xresolution=168, yresolution=176, resolutionunit=2, software=IJ Scan Utility, datetime=2020:04:09 14:55:56], baseline, precision 8, 1535x1444, frames 3

Are there errors in the web browser console?
This I have not yet looked at.

Can you provide me a test file?
Yes, of course. Should it be from one of the four albums used in test 3 ?

**Comment by jcorporation** [comment]
> Yes, of course. Should it be from one of the four albums used in test 3 ?

One that works and one that does not work

**Comment by GK-774** [comment]
Different Browser (a chrome based one on Linux, cache cleared for myMPD and the browser),
and it works for all four :-) . Initial loading is a bit slower (as expected).
I´m sorry not to have tried other browsers after you have fixed the two bugs five days ago,
many thanks for your patience.

**Comment by jcorporation** [comment]
Perfect, you could increase the binary limit to accelerate the mpd albumart and readpicture commands.

**Comment by GK-774** [comment]
increase the binary limit - this would mean editing /var/lib/mympd/state/mpd_binarylimit , correct ? What value would be appropriate (currently it´s 4096) ?

**Comment by jcorporation** [comment]
In v8 this is configurable in the mpd connection dialog under advanced.
