### ISSUE TITLE
Advanced search is not working

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#809]
myMPD version: 9.5.0

**Describe the bug**

Search is not working

**To Reproduce**

1. Go to Advanced Search
2. Type something
3. Nothing happens

**Expected behavior**

Throw some results

**Server plattform (please complete the following information):**
 - OS: Arch
 - MPD version: Latest

**Client plattform (please complete the following information):**
 - Browser [Firefox]
 - Browser version [latest]

No errors at web console or logs...

**Comment by tsunulukai** [comment]
Tried it as well.... it's indeed broken, but there's a way around it:

When you input the search query, it doesn't return any result:
![image](https://user-images.githubusercontent.com/4215150/184512947-b1c0b8ec-02c6-460a-a1c8-abe081b40b74.png)


But if you interact with another interface item once the query has been input once (eg, by pressing enter a second time), then it finally returns the result.

![image](https://user-images.githubusercontent.com/4215150/184513050-e6776ce5-772f-4a12-8e54-c7270ca2e133.png)

**Comment by jcorporation** [comment]
Removed too much code in commit 9713f00240ca7223e0d609c8b0f72244f4f4d44e.

Fixed in devel, please test.

**Comment by Emilot** [comment]
Thank you JC!! Awesome work :)

**Comment by tsunulukai** [comment]
Hi there, just compiled from the latest devel commit (8e31e256a18b8b5f92cb65c133d0595c773a21f0) and I still have the same issue...
For the search to work, I have to press "enter" twice after inputting the search criteria: the first one register the search term and displays it, the second time, the search is effectively run and displays the matching results.

**Comment by Emilot** [comment]
May be a "web cache" issue? My Search works as it is supposed to do...

**Comment by tsunulukai** [comment]
My bad, indeed... reopening the myMPD from a private browser view solves the problem.
So, thanks indeed for the quick fix :)
