### ISSUE TITLE
invalid repo signatures 

### ISSUE THREAD

**Issue by jalsco** [jcorporation/myMPD#947]
**Server plattform (please complete the following information):**
 - OS: DietPi  v8.12.1

Amm getting the following error when I do: `apt update`

```
Err:7 https://download.opensuse.org/repositories/home:/jcorporation/Debian_11  InRelease
  The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
```

**Comment by tsunulukai** [comment]
Same Issue on Debian 11.6

```
# cat /etc/debian_version
11.6

# cat /etc/apt/sources.list.d/jcorporation.list
deb [signed-by=/usr/share/keyrings/jcorporation.github.io.gpg] http://download.opensuse.org/repositories/home:/jcorporation/Debian_11/ ./

# sha256sum /usr/share/keyrings/jcorporation.github.io.gpg
71fb9f3efa221f5fe266376d6519aa875cf693f57faf69cfb8f3dae41a9f3d0b  /usr/share/keyrings/jcorporation.github.io.gpg

# apt update

Err:6 http://download.opensuse.org/repositories/home:/jcorporation/Debian_11 ./ InRelease
  The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/jcorporation/Debian_11 ./ InRelease: The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/jcorporation/Debian_11/./InRelease  The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by jcorporation** [comment]
It seems the key has changed. Reimport as described [here](https://jcorporation.github.io/myMPD/installation/prebuild-packages-debian) and it should work again. I do not know why this has appeared....

**Comment by jcorporation** [comment]
@tsunulukai: Your fix is merged in devel and cherry-picked into master.

**Comment by jcorporation** [comment]
@MichaIng: Issue was reported for DietPi

**Comment by jalsco** [comment]
> It seems the key has changed. Reimport as described [here](https://jcorporation.github.io/myMPD/installation/prebuild-packages-debian) and it should work again. I do not know why this has appeared....

I did all those steps - it did NOT fix the problem.  Please re-open the ticket until it is resolved. 

```
[Wed Jan 04] root@batopi: ~$ curl http://download.opensuse.org/repositories/home:/jcorporation/Debian_11/Release.key | gpg --no-default-keyring --keyring /usr/share/keyrings/jcorporation.github.io.gpg --import
gpg: keybox '/usr/share/keyrings/jcorporation.github.io.gpg' created
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1109  100  1109    0     0   1057      0  0:00:01  0:00:01 --:--:--  1057
gpg: key AA09B8CCE895BD7D: 1 signature not checked due to a missing key
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key AA09B8CCE895BD7D: public key "home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no ultimately trusted keys found
[Wed Jan 04] root@batopi: ~$ gpg --no-default-keyring --keyring /usr/share/keyrings/jcorporation.github.io.gpg --fingerprint
/usr/share/keyrings/jcorporation.github.io.gpg
----------------------------------------------
pub   rsa2048 2018-08-27 [SC] [expires: 2025-02-25]
      A37A ADC4 0A1C C6BE FB75  372F AA09 B8CC E895 BD7D
uid           [ unknown] home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>

[Wed Jan 04] root@batopi: ~$ chmod 644 /usr/share/keyrings/jcorporation.github.io.gpg
[Wed Jan 04] root@batopi: ~$ source /etc/os-release
[Wed Jan 04] root@batopi: ~$ echo $VERSION_ID
11
[Wed Jan 04] root@batopi: ~$ cat <<EOF > /etc/apt/sources.list.d/jcorporation.list
yrings/jcorporat> deb [signed-by=/usr/share/keyrings/jcorporation.github.io.gpg] http://download.opensuse.org/repositories/home:/jcorporation/Debian_$VERSION_ID/ ./
> EOF
 /etc/apt/sources.list.d/jcorporation.list[Wed Jan 04] root@batopi: ~$ cat /etc/apt/sources.list.d/jcorporation.list
deb [signed-by=/usr/share/keyrings/jcorporation.github.io.gpg] http://download.opensuse.org/repositories/home:/jcorporation/Debian_11/ ./
[Wed Jan 04] root@batopi: ~$ apt update
Get:1 http://download.opensuse.org/repositories/home:/jcorporation/Debian_11 ./ InRelease [1532 B]
Hit:2 https://deb.debian.org/debian bullseye InRelease
Hit:4 https://deb.debian.org/debian bullseye-updates InRelease
Get:5 http://download.opensuse.org/repositories/home:/jcorporation/Debian_11 ./ Packages [1799 B]
Get:6 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [7505 B]
Hit:7 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:8 https://deb.debian.org/debian bullseye-backports InRelease
Get:9 https://download.opensuse.org/repositories/home:/jcorporation/Debian_11  InRelease [1532 B]
Hit:3 https://mirror-us-stl1.armbian.airframes.io/apt bullseye InRelease
Err:9 https://download.opensuse.org/repositories/home:/jcorporation/Debian_11  InRelease
  The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
Fetched 12.4 kB in 5s (2589 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.opensuse.org/repositories/home:/jcorporation/Debian_11  InRelease: The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
W: Failed to fetch https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/InRelease  The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
[Wed Jan 04] root@batopi: ~$
```

**Comment by tsunulukai** [comment]
In the error message you get, EXPKEYSIG means the signature key is expired. Could you try deleting /usr/share/keyrings/jcorporation.github.io.gpg before retrying the procedure ?

I had the exact same error as you did and solved it by deleting the keyfile and reimporting it.

**Comment by jalsco** [comment]
I just did that - and still has same problem. 

```
[Wed Jan 04] root@batopi: ~$ rm  /usr/share/keyrings/jcorporation.github.io.gpg
rm: remove regular file '/usr/share/keyrings/jcorporation.github.io.gpg'? y
[Wed Jan 04] root@batopi: ~$ curl http://download.opensuse.org/repositories/home:/jcorporation/Debian_11/Release.key | gpg --no-default-keyring --keyring /usr/share/keyrings/jcorporation.github.io.gpg --import
gpg: keybox '/usr/share/keyrings/jcorporation.github.io.gpg' created
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1109  100  1109    0     0    951      0  0:00:01  0:00:01 --:--:--   952
gpg: key AA09B8CCE895BD7D: 1 signature not checked due to a missing key
gpg: key AA09B8CCE895BD7D: public key "home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no ultimately trusted keys found
[Wed Jan 04] root@batopi: ~$ gpg --no-default-keyring --keyring /usr/share/keyrings/jcorporation.github.io.gpg --fingerprint
/usr/share/keyrings/jcorporation.github.io.gpg
----------------------------------------------
pub   rsa2048 2018-08-27 [SC] [expires: 2025-02-25]
      A37A ADC4 0A1C C6BE FB75  372F AA09 B8CC E895 BD7D
uid           [ unknown] home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>

[Wed Jan 04] root@batopi: ~$ chmod 644 /usr/share/keyrings/jcorporation.github.io.gpg
[Wed Jan 04] root@batopi: ~$ source /etc/os-release
ON_ID[Wed Jan 04] root@batopi: ~$ echo $VERSION_ID
11
[Wed Jan 04] root@batopi: ~$ cat <<EOF > /etc/apt/sources.list.d/jcorporation.list
> deb [signed-by=/usr/share/keyrings/jcorporation.github.io.gpg] http://download.opensuse.org/repositories/home:/jcorporation/Debian_$VERSION_ID/ ./
> EOF
[Wed Jan 04] root@batopi: ~$ cat /etc/apt/sources.list.d/jcorporation.list
deb [signed-by=/usr/share/keyrings/jcorporation.github.io.gpg] http://download.opensuse.org/repositories/home:/jcorporation/Debian_11/ ./
[Wed Jan 04] root@batopi: ~$
[Wed Jan 04] root@batopi: ~$ apt update
Hit:1 https://deb.debian.org/debian bullseye InRelease
Hit:3 https://deb.debian.org/debian bullseye-updates InRelease
Get:4 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [7505 B]
Hit:5 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:6 https://deb.debian.org/debian bullseye-backports InRelease
Get:7 https://download.opensuse.org/repositories/home:/jcorporation/Debian_11  InRelease [1532 B]
Get:8 http://download.opensuse.org/repositories/home:/jcorporation/Debian_11 ./ InRelease [1532 B]
Hit:2 https://mirror-us-stl1.armbian.airframes.io/apt bullseye InRelease
Err:7 https://download.opensuse.org/repositories/home:/jcorporation/Debian_11  InRelease
  The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
Fetched 10.6 kB in 5s (2128 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.opensuse.org/repositories/home:/jcorporation/Debian_11  InRelease: The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
W: Failed to fetch https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/InRelease  The following signatures were invalid: EXPKEYSIG AA09B8CCE895BD7D home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
[Wed Jan 04] root@batopi: ~$
```

**Comment by jcorporation** [comment]
Remove the keyring file and check if the error message changes.

**Comment by MichaIng** [comment]
Before fixing, can you show the output of the following command, so we can do a pre-patch with next DietPi update to update the key for everyone, if expired.
```sh
apt-key list
```

If installed via `dietpi-software`, the key is installed via:
```sh
curl -sSfL 'https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/Release.key' | gpg --dearmor -o /etc/apt/trusted.gpg.d/dietpi-mympd.gpg --yes
```
and the repo is stored to `/etc/apt/sources.list.d/dietpi-mympd.list`. You currently have both duplicated, so run the above command, then remove the duplications:
```sh
rm /usr/share/keyrings/jcorporation.github.io.gpg /etc/apt/sources.list.d/jcorporation.list
apt update
```

**Comment by jalsco** [comment]
```
[Thu Jan 05] root@batopi: ~$ apt-key list
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2015-03-16 [SC]
      DF00 FAF1 C577 104B 50BF  1D00 93D6 889F 9F0E 78D5
uid           [ unknown] Igor Pecovnik (Ljubljana, Slovenia) <igor.pecovnik@gmail.com>
sub   rsa4096 2015-03-16 [E]

pub   rsa4096 2016-04-01 [SC]
      6576 0C51 EDEA 2017 CEA2  CA15 155B 6D79 CA56 EA34
uid           [ unknown] Caddy Web Server <contact@caddyserver.com>
sub   rsa4096 2020-12-29 [S] [expires: 2025-12-28]

pub   rsa3072 2020-11-24 [SC] [expired: 2022-11-24]
      466B 1E7F 6809 6652 1384  8FCA B99C 4BEF EC47 E96E
uid           [ expired] Radxa <dev@radxa.com>

/etc/apt/trusted.gpg.d/caddy-stable.asc
---------------------------------------
pub   rsa4096 2016-04-01 [SC]
      6576 0C51 EDEA 2017 CEA2  CA15 155B 6D79 CA56 EA34
uid           [ unknown] Caddy Web Server <contact@caddyserver.com>
sub   rsa4096 2020-12-29 [S] [expires: 2025-12-28]

/etc/apt/trusted.gpg.d/debian-archive-bullseye-automatic.gpg
------------------------------------------------------------
pub   rsa4096 2021-01-17 [SC] [expires: 2029-01-15]
      1F89 983E 0081 FDE0 18F3  CC96 73A4 F27B 8DD4 7936
uid           [ unknown] Debian Archive Automatic Signing Key (11/bullseye) <ftpmaster@debian.org>
sub   rsa4096 2021-01-17 [S] [expires: 2029-01-15]

/etc/apt/trusted.gpg.d/debian-archive-bullseye-security-automatic.gpg
---------------------------------------------------------------------
pub   rsa4096 2021-01-17 [SC] [expires: 2029-01-15]
      AC53 0D52 0F2F 3269 F5E9  8313 A484 4904 4AAD 5C5D
uid           [ unknown] Debian Security Archive Automatic Signing Key (11/bullseye) <ftpmaster@debian.org>
sub   rsa4096 2021-01-17 [S] [expires: 2029-01-15]

/etc/apt/trusted.gpg.d/debian-archive-bullseye-stable.gpg
---------------------------------------------------------
pub   rsa4096 2021-02-13 [SC] [expires: 2029-02-11]
      A428 5295 FC7B 1A81 6000  62A9 605C 66F0 0D6C 9793
uid           [ unknown] Debian Stable Release Key (11/bullseye) <debian-release@lists.debian.org>

/etc/apt/trusted.gpg.d/debian-archive-buster-automatic.gpg
----------------------------------------------------------
pub   rsa4096 2019-04-14 [SC] [expires: 2027-04-12]
      80D1 5823 B7FD 1561 F9F7  BCDD DC30 D7C2 3CBB ABEE
uid           [ unknown] Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>
sub   rsa4096 2019-04-14 [S] [expires: 2027-04-12]

/etc/apt/trusted.gpg.d/debian-archive-buster-security-automatic.gpg
-------------------------------------------------------------------
pub   rsa4096 2019-04-14 [SC] [expires: 2027-04-12]
      5E61 B217 265D A980 7A23  C5FF 4DFA B270 CAA9 6DFA
uid           [ unknown] Debian Security Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>
sub   rsa4096 2019-04-14 [S] [expires: 2027-04-12]

/etc/apt/trusted.gpg.d/debian-archive-buster-stable.gpg
-------------------------------------------------------
pub   rsa4096 2019-02-05 [SC] [expires: 2027-02-03]
      6D33 866E DD8F FA41 C014  3AED DCC9 EFBF 77E1 1517
uid           [ unknown] Debian Stable Release Key (10/buster) <debian-release@lists.debian.org>

/etc/apt/trusted.gpg.d/debian-archive-stretch-automatic.gpg
-----------------------------------------------------------
pub   rsa4096 2017-05-22 [SC] [expires: 2025-05-20]
      E1CF 20DD FFE4 B89E 8026  58F1 E0B1 1894 F66A EC98
uid           [ unknown] Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>
sub   rsa4096 2017-05-22 [S] [expires: 2025-05-20]

/etc/apt/trusted.gpg.d/debian-archive-stretch-security-automatic.gpg
--------------------------------------------------------------------
pub   rsa4096 2017-05-22 [SC] [expires: 2025-05-20]
      6ED6 F5CB 5FA6 FB2F 460A  E88E EDA0 D238 8AE2 2BA9
uid           [ unknown] Debian Security Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>
sub   rsa4096 2017-05-22 [S] [expires: 2025-05-20]

/etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg
--------------------------------------------------------
pub   rsa4096 2017-05-20 [SC] [expires: 2025-05-18]
      067E 3C45 6BAE 240A CEE8  8F6F EF0F 382A 1A7B 6500
uid           [ unknown] Debian Stable Release Key (9/stretch) <debian-release@lists.debian.org>

/etc/apt/trusted.gpg.d/dietpi-armbian.gpg
-----------------------------------------
pub   rsa4096 2015-03-16 [SC]
      DF00 FAF1 C577 104B 50BF  1D00 93D6 889F 9F0E 78D5
uid           [ unknown] Igor Pecovnik (Ljubljana, Slovenia) <igor.pecovnik@gmail.com>
sub   rsa4096 2015-03-16 [E]

/etc/apt/trusted.gpg.d/dietpi-mympd.gpg
---------------------------------------
pub   rsa2048 2018-08-27 [SC] [expired: 2023-01-01]
      A37A ADC4 0A1C C6BE FB75  372F AA09 B8CC E895 BD7D
uid           [ expired] home:jcorporation OBS Project <home:jcorporation@build.opensuse.org>

```

**Comment by jalsco** [comment]
```
[Thu Jan 05] root@batopi: ~$ curl -sSfL 'https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/Release.key' | gpg --dearmor -o /etc/apt/trusted.gpg.d/dietpi-mympd.gpg --yes
[Thu Jan 05] root@batopi: ~$ rm /usr/share/keyrings/jcorporation.github.io.gpg /etc/apt/sources.list.d/jcorporation.list
rm: remove regular file '/usr/share/keyrings/jcorporation.github.io.gpg'? y
rm: remove regular file '/etc/apt/sources.list.d/jcorporation.list'? y
[Thu Jan 05] root@batopi: ~$ apt update
Hit:1 https://deb.debian.org/debian bullseye InRelease
Get:3 https://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [7505 B]
Hit:5 https://deb.debian.org/debian-security bullseye-security InRelease
Get:6 https://download.opensuse.org/repositories/home:/jcorporation/Debian_11  InRelease [1532 B]
Get:7 https://deb.debian.org/debian bullseye-backports InRelease [49.0 kB]
Hit:2 https://mirror-us-stl1.armbian.airframes.io/apt bullseye InRelease
Fetched 102 kB in 5s (21.5 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
```

Well, that's good ! no error message . Thanks @MichaIng  😁🙏🏻
